### ISSUE TITLE
Tests failing when triggering builds

### ISSUE THREAD

**Issue by Abhimanyu121** [eth-infinitism/bundler-test-executor#24]
I forked this repo and triggered the tests without changing anything. Most of the bundlers are failing almost all tests, can someone please tell me if I am missing anything?
Here is a link to job-execution
https://github.com/Abhimanyu121/bundler-test-executor/actions/runs/4994721208/jobs/8945673718#step:14:18

**Comment by drortirosh** [comment]
the "push updates" of the results should fail, as you are on a separate repo with no permission to update the master.
the "clone and update" step outpus shows the results, which are all sucessful
